version: "3.8"

services:
  web:
    image: shui
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/scss:/app/scss
    ports:
      - 8080:8080
    command: npm run serve

  api:
    image: api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: ./backend/.env
    volumes:
      - ./backend/routes:/app/routes:ro
      - ./backend/db:/app/db
    
    ports:
      - 3000:3000
